import './models/produto.dart';

// ignore: constant_identifier_names
const MOCK_PRODUTOS_DATA = [
  Produto(
    id: 'p1',
    nome: 'Arroz',
    descricao: 'Arroz branco',
    imagem: 'assets/images/arroz.jpg',
    preco: '10.00',
    quantidade: '10',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 1',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 1',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p2',
    nome: 'Feijão',
    descricao: 'Feijão carioca',
    imagem: 'assets/images/feijao.jpg',
    preco: '5.00',
    quantidade: '5',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 2',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 2',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p3',
    nome: 'Macarrão',
    descricao: 'Macarrão espaguete',
    imagem: 'assets/images/macarrao.jpg',
    preco: '3.00',
    quantidade: '3',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 3',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 3',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p4',
    nome: 'Óleo',
    descricao: 'Óleo de soja',
    imagem: 'assets/images/oleo.jpg',
    preco: '7.00',
    quantidade: '7',
    unidade: 'L',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 4',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 4',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p5',
    nome: 'Sal',
    descricao: 'Sal refinado',
    imagem: 'assets/images/sal.jpg',
    preco: '2.00',
    quantidade: '2',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 5',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 5',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p6',
    nome: 'Açúcar',
    descricao: 'Açúcar refinado',
    imagem: 'assets/images/acucar.jpg',
    preco: '4.00',
    quantidade: '4',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 6',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 6',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p7',
    nome: 'Café',
    descricao: 'Café torrado e moído',
    imagem: 'assets/images/cafe.jpg',
    preco: '6.00',
    quantidade: '6',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 7',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 7',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p8',
    nome: 'Leite',
    descricao: 'Leite integral',
    imagem: 'assets/images/leite.jpg',
    preco: '8.00',
    quantidade: '8',
    unidade: 'L',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 8',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 8',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p9',
    nome: 'Margarina',
    descricao: 'Margarina com sal',
    imagem: 'assets/images/margarina.jpg',
    preco: '9.00',
    quantidade: '9',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 9',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 9',
    observacao: 'Sem observações',
  ),
  Produto(
    id: 'p10',
    nome: 'Pão',
    descricao: 'Pão francês',
    imagem: 'assets/images/pao.jpg',
    preco: '1.00',
    quantidade: '1',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 10',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 10',
    observacao: 'Sem observações',
  ),
];
