import './models/produto.dart';

// ignore: constant_identifier_names
var MOCK_PRODUTOS_DATA = [
  Produto(
    id: '1',
    tipo: Tipos.vinho.name,
    nome: 'Vinho Sao Francisco',
    descricao: 'Vinho tinto seco',
    imagem: 'assets/images/vinho.jpg',
    valorCompraTotal: '50.00 ',
    preco: '10.00',
    quantidade: '10',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Washgtom',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 1',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '2',
    tipo: Tipos.cachaca.name,
    nome: 'Cachaça Ypioca',
    descricao: 'Cachaça envelhecida',
    imagem: 'assets/images/cachaca.jpg',
    valorCompraTotal: '25.00',
    preco: '5.00',
    quantidade: '5',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 2',
    data: '01/02/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 2',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '3',
    tipo: Tipos.vodka.name,
    nome: 'Vodka Smirnoff',
    descricao: 'Vodka importada',
    imagem: 'assets/images/vodka.jpg',
    valorCompraTotal: '75.00',
    preco: '15.00',
    quantidade: '15',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 3',
    data: '01/03/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 3',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '4',
    tipo: Tipos.whisky.name,
    nome: 'Whisky Johnnie Walker',
    descricao: 'Whisky escocês',
    imagem: 'assets/images/whisky.jpg',
    valorCompraTotal: '100.00',
    preco: '20.00',
    quantidade: '20',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 4',
    data: '01/04/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 4',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '5',
    tipo: Tipos.cerveja.name,
    nome: 'Cerveja Skol',
    descricao: 'Cerveja pilsen',
    imagem: 'assets/images/cerveja.jpg',
    valorCompraTotal: '10.00',
    preco: '2.00',
    quantidade: '20',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 5',
    data: '01/05/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 5',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '6',
    tipo: Tipos.gelo.name,
    nome: 'Gelo',
    descricao: 'Gelo em cubos',
    imagem: 'assets/images/gelo.jpg',
    valorCompraTotal: '1.00',
    preco: '1.00',
    quantidade: '5',
    unidade: 'kg',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 6',
    data: '01/06/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 6',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '7',
    tipo: Tipos.outros.name,
    nome: 'Amendoin',
    descricao: 'Amendoin torrado',
    imagem: 'assets/images/amendoin.jpg',
    valorCompraTotal: '7.00',
    preco: '7.00',
    quantidade: '7',
    unidade: 'kg',
    categoria: 'Alimento',
    fornecedor: 'Fornecedor 7',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 7',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '8',
    tipo: Tipos.rum.name,
    nome: 'Rum Motilla',
    descricao: 'Rum envelhecido',
    imagem: 'assets/images/rum.jpg',
    valorCompraTotal: '8.00',
    preco: '8.00',
    quantidade: '8',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 8',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 8',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '9',
    tipo: Tipos.semAlcool.name,
    nome: 'Refrigerante',
    descricao: 'Refrigerante de cola',
    imagem: 'assets/images/refrigerante.jpg',
    valorCompraTotal: '3.00',
    preco: '3.00',
    quantidade: '3',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 9',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 9',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '10',
    tipo: Tipos.vinho.name,
    nome: 'Vinho Aurora',
    descricao: 'Vinho tinto suave',
    imagem: 'assets/images/vinho_branco.jpg',
    valorCompraTotal: '4.00',
    preco: '4.00',
    quantidade: '4',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 10',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 10',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '11',
    tipo: Tipos.tequila.name,
    nome: 'Tequila Jose Cuervo',
    descricao: 'Tequila mexicana',
    imagem: 'assets/images/tequila.jpg',
    valorCompraTotal: '5.00',
    preco: '5.00',
    quantidade: '5',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 11',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 11',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '12',
    tipo: Tipos.absinto.name,
    nome: 'Absinto',
    descricao: 'Absinto importado',
    imagem: 'assets/images/absinto.jpg',
    valorCompraTotal: '6.00',
    preco: '6.00',
    quantidade: '6',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 12',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 12',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '13',
    tipo: Tipos.cerveja.name,
    nome: 'Cerveja Heineken',
    descricao: 'Cerveja pilsen',
    imagem: 'assets/images/cerveja_heineken.jpg',
    valorCompraTotal: '7.00',
    preco: '7.00',
    quantidade: '7',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 13',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 13',
    observacao: 'Sem observações',
  ),
  Produto(
    id: '14',
    tipo: Tipos.cerveja.name,
    nome: 'Cerveja Budweiser',
    descricao: 'Cerveja pilsen',
    imagem: 'assets/images/cerveja_budweiser.jpg',
    valorCompraTotal: '8.00',
    preco: '8.00',
    quantidade: '8',
    unidade: 'L',
    categoria: 'Bebida',
    fornecedor: 'Fornecedor 14',
    data: '01/01/2021',
    validade: '01/01/2022',
    lote: '123456',
    local: 'Prateleira 14',
    observacao: 'Sem observações',
  ),
];
